name: "release"
on:
    push:
        branches:
            - master
jobs:
    test:
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: Install node 20.10.0
              uses: actions/setup-node@v4
              with:
                node-version: "20.10.0"
            - name: Checking node and npm version
              run: node -v && npm -v
            - name: Verify the working repository
              run: echo $GITHUB_WORKSPACE
            - name: Check all files within the directory
              run: ls -a
