name: "release"
on:
    push:
        branches:
            - master
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: Verify the working repository
              run: echo $GITHUB_WORKSPACE

